name: Test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: Run coverage
        run: go test -cover -coverprofile=coverage.txt -count=1 -short
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
